### ISSUE TITLE
No carga el proyecto por que el states.js no tiene nombre

### ISSUE THREAD

**Issue by RicardoFazzi** [darioodiaz/fapb#1]
define([], function() {
    var constructor = {};
    constructor.init = function($stateProvider) {
        $stateProvider.state("index", {
            state: "index",
            url: "/"
        });
    };
    return constructor;
});

Hay que agregarle nombre al estado.

**Comment by darioodiaz** [comment]
fixeado en https://github.com/darioodiaz/fapb/pull/2

gracias por el aporte
